const data = [
  {
    amount: '0',
    ticker: 'rep',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usdc_e',
    versions: [
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: false,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'not',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'ton',
        name: 'TON',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ray',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'eur',
    versions: [],
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['fiat', 'base'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bnb',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ldo',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'wen',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'hmstr',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'ton',
        name: 'TON',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: false,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bch',
    versions: [
      {
        address: null,
        version: 'bch',
        name: 'Bitcoin Cash',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: '1inch',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usdp',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pol',
    versions: [
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'myro',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'om',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bars',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'doge',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ada',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'snx',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'atom',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bonus',
    versions: [],
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: false,
    marketToEnabled: true,
    tags: ['bonus'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ilv',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'fil',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pyusd',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: true,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bttc',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'xrp',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'xrp',
        name: 'Ripple',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: false,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'inj',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'mkr',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'gmt',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'trx',
    versions: [
      {
        address: null,
        version: 'trc20',
        name: 'TRON (TRC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'jup',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'eigen',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 's',
    versions: [
      {
        address: null,
        version: 'sonic',
        name: 'Sonic',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'xtz',
    versions: [
      {
        address: null,
        version: 'xtz',
        name: 'Tezos',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'move',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'aave',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'floki',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pepe',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'yhdlbeta',
    versions: [],
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: false,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'jasmy',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'yfi',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'tusd',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'eos',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'eos',
        name: 'EOSIO',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'flow',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'cati',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'ton',
        name: 'TON',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'axs',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'render',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'silly',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'link',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ondo',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'dash',
    versions: [
      {
        address: null,
        version: 'dash',
        name: 'Dash',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'uni',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'me',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'sgb',
    versions: [
      {
        address: null,
        version: 'sgb20',
        name: 'Songbird',
      },
    ],
    address: null,
    createEnabled: false,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'trump',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'token'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'sol',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ftt',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'dai',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ethw',
    versions: [
      {
        address: null,
        version: 'ethw',
        name: 'Ethereum PoW',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ape',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'lista',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ht',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'paxg',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usdc',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: false,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ena',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'wld',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'cake',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'sand',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ltc',
    versions: [
      {
        address: null,
        version: 'ltc',
        name: 'Litecoin',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'dogs',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'ton',
        name: 'TON',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bnt',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'vet',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'sushi',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pyth',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'fet',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'mnt',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'mana',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'w',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'dot',
    versions: [
      {
        address: null,
        version: 'dot',
        name: 'Polkadot',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pengu',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'strk',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'omg',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'husd',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['stableCoin'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'wif',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'tremp',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'xlm',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'xlm',
        name: 'Stellar',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'avax',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'avax',
        name: 'Avax',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bonk',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'near',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'btc',
    versions: [
      {
        address: null,
        version: 'origin',
        name: 'Bitcoin (Main)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'base'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'zil',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'eurs',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: false,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'banana',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ftm',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: false,
    withdrawEnabled: false,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'bat',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'zro',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'grt',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'yhdl',
    versions: [
      {
        address: null,
        version: 'arbitrum',
        name: 'Arbitrum',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: false,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'qnt',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'comp',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'meme',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'gala',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'egld',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'ton',
    versions: [
      {
        address: null,
        extraId: null,
        version: 'ton',
        name: 'TON',
      },
    ],
    address: null,
    extraId: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'shib',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'io',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'people',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'eth',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'flr',
    versions: [
      {
        address: null,
        version: 'flr',
        name: 'Flare',
      },
    ],
    address: null,
    createEnabled: false,
    depositEnabled: false,
    withdrawEnabled: true,
    loanEnabled: false,
    turboEnabled: false,
    hodlEnabled: false,
    marketEnabled: false,
    marketToEnabled: false,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'popcat',
    versions: [
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usual',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'chf',
    versions: [],
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['fiat'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'imx',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: false,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usd',
    versions: [],
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['fiat', 'base'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'usdt',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
      {
        address: null,
        version: 'trc20',
        name: 'TRON (TRC-20)',
      },
      {
        address: null,
        version: 'polygon',
        name: 'Polygon (previously Matic Network)',
      },
      {
        address: null,
        version: 'sol',
        name: 'Solana',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto', 'stableCoin'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'zrx',
    versions: [
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'gbp',
    versions: [],
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['fiat'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
  {
    amount: '0',
    ticker: 'pendle',
    versions: [
      {
        address: null,
        version: 'bep20',
        name: 'BNB Smart Chain (BEP-20)',
      },
      {
        address: null,
        version: 'erc20',
        name: 'Ethereum (ERC-20)',
      },
    ],
    address: null,
    createEnabled: true,
    depositEnabled: true,
    withdrawEnabled: true,
    loanEnabled: true,
    turboEnabled: true,
    hodlEnabled: true,
    marketEnabled: true,
    marketToEnabled: true,
    tags: ['crypto'],
    chartEnabled: true,
    umaEnabled: true,
    visible: true,
    products: [],
    hodlsInputAmount: '0',
    amountForSavings: '0',
    capital: {
      btc: '0',
      eur: '0',
      usd: '0',
    },
  },
];

const result = data.map((el) => ({ ticker: el.ticker, tags: el.tags, versions: el.versions.map((ver) => ({version: ver.version, name: ver.name})), isVisible: el.visible }));

import { writeFileSync } from 'node:fs';
writeFileSync('./tickersTypes.json', JSON.stringify({ data: result }));
